// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRCGZ3vi-8mDZaDaSJgA0zrMmCMQoy178',
    appId: '1:2286440738:web:a402629d66bc1f4c69157b',
    messagingSenderId: '2286440738',
    projectId: 'gkrank',
    authDomain: 'gkrank.firebaseapp.com',
    storageBucket: 'gkrank.firebasestorage.app',
    measurementId: 'G-GMTGGQW8W7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1J9GJOiiI5sMm1F8uBLBTrviZYKZglHU',
    appId: '1:2286440738:android:9a0dd349cf867eae69157b',
    messagingSenderId: '2286440738',
    projectId: 'gkrank',
    storageBucket: 'gkrank.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9mvgn9uX-3WBSr1f6JXRv7gPsHifj61Y',
    appId: '1:2286440738:ios:223821191955f9ec69157b',
    messagingSenderId: '2286440738',
    projectId: 'gkrank',
    storageBucket: 'gkrank.firebasestorage.app',
    iosBundleId: 'com.cybomb.gkrank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9mvgn9uX-3WBSr1f6JXRv7gPsHifj61Y',
    appId: '1:2286440738:ios:223821191955f9ec69157b',
    messagingSenderId: '2286440738',
    projectId: 'gkrank',
    storageBucket: 'gkrank.firebasestorage.app',
    iosBundleId: 'com.cybomb.gkrank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRCGZ3vi-8mDZaDaSJgA0zrMmCMQoy178',
    appId: '1:2286440738:web:70ee263897b6b8da69157b',
    messagingSenderId: '2286440738',
    projectId: 'gkrank',
    authDomain: 'gkrank.firebaseapp.com',
    storageBucket: 'gkrank.firebasestorage.app',
    measurementId: 'G-3XZQYJL68D',
  );
}
